### ISSUE TITLE
possible source of ocp#181?

### ISSUE THREAD

**Issue by j6k4m8** [neurodata/kasthuri2015#11]
i think [this](https://github.com/openconnectome/kasthuri2015/blob/master/ramonify/ramonify_kasthuri.m#L225) is the issue.

Doing more dissecting now, but it'd explain https://github.com/openconnectome/open-connectome/issues/181

**Comment by alexbaden** [comment]
What does setSegments look like? If it converts the array to a string
before storing in the HDF5 file for upload (which I bet it does, because
segments is a key-value pair), then maybe we just need to remove the "[]"
from... somewhere?

**Comment by j6k4m8** [comment]
my thought as well. possibly as simple as stripping the string...

@willgray are we ok with editing cajal code if it is indeed a cajal issue?

**Comment by j6k4m8** [comment]
revision: it just sets the `.segments` to whatever it's passed:

https://github.com/openconnectome/CAJAL/blob/master/api/matlab/ramon/RAMONNeuron.m#L96

**Comment by wrgr** [comment]
This is indeed a cajal bug, although we might issue a parallel feature request for the OCP backend to sanitize inputs.  

I tested to confirm I was properly setting the neuron.segments field with numbers on a fresh token/channel.  Same error.  So somewhere in the packaging things are getting converted to strings and broken.  

This didn't come up earlier because either things changed on the backend or CAJAL and we didn't test for it and/or because our workflows usually don't actually pull neurons back down for computational efficiency reasons (like when building a graph).  

I'll look at this more with Jordan this week while doing kasthuri queries.  @alexbaden  - will keep you updated.  May involve a small CAJAL patch assuming it doesn't break anything else.

**Comment by wrgr** [comment]
This is interesting.  Using same CAJAL and same everything, the error no longer exists.  After lots of debugging, I deleted and recreated the channels using the _exact_ same committed code (afaict) and now can retrieve neurons with no issues. 

Super weird.  But not broken.  Same token/channel - can someone look and see if they see the string behavior on the backend?  @kunallillaney - you may or may not care about this.

Perhaps a case to sanitize inputs on the backend/frontend?

**Comment by wrgr** [comment]
fixed. afaict.
